#!/usr/bin/env bash
set -uo pipefail
# shellcheck source=lib/assert.sh
. "$ZRO_TEST_ROOT/lib/assert.sh"
# shellcheck source=../lib/core.sh
. "$ZRO_SRC/lib/core.sh"
# shellcheck source=../lib/validate.sh
. "$ZRO_SRC/lib/validate.sh"

it "accepts ordinary addresses"
assert_ok zro_validate_email 'ahmet.yilmaz@example.com'
assert_ok zro_validate_email 'a@b.co'
assert_ok zro_validate_email 'user+tag_1%x@mail.example.co.uk'

it "rejects shell metacharacters"
assert_status "$ZRO_E_INPUT" zro_validate_email 'a@b.com; rm -rf /'
assert_status "$ZRO_E_INPUT" zro_validate_email 'a@b.com && id'
assert_status "$ZRO_E_INPUT" zro_validate_email 'a@b.com | tee /tmp/x'
# The single quotes are the point: these payloads must reach the validator
# unexpanded, exactly as an operator would type them into the prompt.
# shellcheck disable=SC2016
assert_status "$ZRO_E_INPUT" zro_validate_email '$(id)@b.com'
# shellcheck disable=SC2016
assert_status "$ZRO_E_INPUT" zro_validate_email '`id`@b.com'
assert_status "$ZRO_E_INPUT" zro_validate_email 'a@b.com > /etc/passwd'

it "rejects quotes and backslashes"
assert_status "$ZRO_E_INPUT" zro_validate_email 'a"b@c.com'
assert_status "$ZRO_E_INPUT" zro_validate_email 'a\b@c.com'
assert_status "$ZRO_E_INPUT" zro_validate_email "a'b@c.com"

it "rejects whitespace and embedded newlines"
assert_status "$ZRO_E_INPUT" zro_validate_email 'a b@c.com'
assert_status "$ZRO_E_INPUT" zro_validate_email $'a@b.com\nrm -rf /'
assert_status "$ZRO_E_INPUT" zro_validate_email $'a@b.com\t-l'
assert_status "$ZRO_E_INPUT" zro_validate_email ' a@b.com'
assert_status "$ZRO_E_INPUT" zro_validate_email 'a@b.com '

it "rejects malformed addresses"
assert_status "$ZRO_E_INPUT" zro_validate_email ''
assert_status "$ZRO_E_INPUT" zro_validate_email 'nobody'
assert_status "$ZRO_E_INPUT" zro_validate_email '@example.com'
assert_status "$ZRO_E_INPUT" zro_validate_email 'a@'
assert_status "$ZRO_E_INPUT" zro_validate_email 'a@b'
assert_status "$ZRO_E_INPUT" zro_validate_email 'a@@b.com'
assert_status "$ZRO_E_INPUT" zro_validate_email 'a@b..com'
assert_status "$ZRO_E_INPUT" zro_validate_email 'a@-b.com'
assert_status "$ZRO_E_INPUT" zro_validate_email 'a@b-.com'
assert_status "$ZRO_E_INPUT" zro_validate_email 'a@b.c'

it "rejects an argument that starts with a dash"
assert_status "$ZRO_E_INPUT" zro_validate_email '-l@b.com'

it "enforces length limits"
long_local=$(printf 'a%.0s' {1..65})
assert_status "$ZRO_E_INPUT" zro_validate_email "${long_local}@b.com"
long_label=$(printf 'a%.0s' {1..64})
assert_status "$ZRO_E_INPUT" zro_validate_email "a@${long_label}.com"

it "accepts a label of exactly the maximum length"
max_label=$(printf 'a%.0s' {1..63})
assert_ok zro_validate_email "a@${max_label}.com"

# Every filter the delivery tracer accepts is a Perl regular expression, so a
# validated address still has to be escaped before it is used as one. One row per
# metacharacter: the text an operator typed, then the pattern it must become.
it "quotes every regular-expression metacharacter"
while IFS='|' read -r input want; do
  [ -n "$input" ] || continue
  assert_out_eq "$want" zro_regex_quote "$input"
done <<'EOF'
a.b|a\.b
a+b|a\+b
a*b|a\*b
a?b|a\?b
a^b|a\^b
a$b|a\$b
a(b|a\(b
a)b|a\)b
a[b|a\[b
a]b|a\]b
a{b|a\{b
a}b|a\}b
a/b|a\/b
a\b|a\\b
EOF
# The alternation metacharacter cannot travel through a pipe-separated table.
assert_out_eq 'a\|b' zro_regex_quote 'a|b'

it "leaves text that is not a metacharacter alone"
assert_out_eq 'ahmet' zro_regex_quote 'ahmet'
assert_out_eq '' zro_regex_quote ''
assert_out_eq '' zro_regex_quote
assert_out_eq 'ahmet_yilmaz-1%x@example' zro_regex_quote 'ahmet_yilmaz-1%x@example'

# The address from ADR-0002: it passes validation, and used unescaped as a
# pattern it fails to match itself — a false negative on the one question the
# delivery trace exists to answer. Bash's own engine is the independent judge
# here, not our escaping code.
it "an address with a quantifier in it matches itself once quoted"
quoted=$(zro_regex_quote 'ali+fatura@example.com')
raw='ali+fatura@example.com'
assert_ok zro_validate_email 'ali+fatura@example.com'
if [[ 'ali+fatura@example.com' =~ ^${quoted}$ ]]; then
  zro_t_pass
else
  zro_t_fail "quoted address does not match itself: $quoted"
fi
if [[ 'ali+fatura@example.com' =~ ^${raw}$ ]]; then
  zro_t_fail "unquoted address matched itself; the table above proves nothing"
else
  zro_t_pass
fi
# Quoted, it is a literal and matches nothing wider than itself.
if [[ 'aliiifatura@example.com' =~ ^${quoted}$ ]]; then
  zro_t_fail "quoted address widened into a pattern: $quoted"
else
  zro_t_pass
fi

# The message-id filter is the only one whose value is not an address. A real
# identifier is generated by whatever agent first touched the message, and there
# is no shape they agree on — so the character set is permissive on purpose, and
# what this table refuses is what would stop being ONE VALUE by the time it
# reached a command line, a report or a log line.
it "accepts message-ids as they are really generated"
assert_ok zro_validate_msgid 'CAabc123@example.com'
assert_ok zro_validate_msgid '20260728080000.A1B2C3@mail.example.com'
# Not an address, and not required to be one: an id may carry anything its
# generator felt like putting in it, and refusing those would answer "invalid
# input" to an identifier the server itself recorded.
# Single-quoted for the reason the address table gives: the payload has to reach
# the validator exactly as an operator would paste it, unexpanded.
# shellcheck disable=SC2016
assert_ok zro_validate_msgid 'a$b%c!d*e+f@example.com'
assert_ok zro_validate_msgid "op'aq@example.com"
assert_ok zro_validate_msgid '1234567890'
assert_ok zro_validate_msgid 'no-at-sign-at-all'

it "rejects control characters and newlines"
# A newline in a filter is a second line in every log message this program
# writes and a second value on the screen that reports what was searched. NUL is
# absent from this table on purpose: it cannot travel through an argument vector
# at all, so there is nothing here that could carry one.
assert_status "$ZRO_E_INPUT" zro_validate_msgid $'CAabc\n123@example.com'
assert_status "$ZRO_E_INPUT" zro_validate_msgid $'CAabc\t123@example.com'
assert_status "$ZRO_E_INPUT" zro_validate_msgid $'CAabc\r123@example.com'
assert_status "$ZRO_E_INPUT" zro_validate_msgid $'CAabc\x1b[2J@example.com'
assert_status "$ZRO_E_INPUT" zro_validate_msgid $'CAabc123@example.com\n'
assert_status "$ZRO_E_INPUT" zro_validate_msgid $'\n'

it "rejects anything that is more than one value"
# The usual paste: the header line, label and all. Refusing it is the point —
# used as a pattern it would match nothing, and an empty trace reads as proof
# the message never arrived.
assert_status "$ZRO_E_INPUT" zro_validate_msgid 'Message-ID: <CAabc123@example.com>'
assert_status "$ZRO_E_INPUT" zro_validate_msgid 'CAabc 123@example.com'
assert_status "$ZRO_E_INPUT" zro_validate_msgid ' CAabc123@example.com'
assert_status "$ZRO_E_INPUT" zro_validate_msgid 'CAabc123@example.com '

it "rejects a message-id that starts with a dash"
# Read as a flag by any command line it reaches, exactly as for an address.
assert_status "$ZRO_E_INPUT" zro_validate_msgid '-i'
assert_status "$ZRO_E_INPUT" zro_validate_msgid '--sender'
assert_status "$ZRO_E_INPUT" zro_validate_msgid '-CAabc123@example.com'

it "enforces a length limit"
assert_ok zro_validate_msgid "$(printf 'a%.0s' {1..512})"
assert_status "$ZRO_E_INPUT" zro_validate_msgid "$(printf 'a%.0s' {1..513})"

it "rejects an empty message-id"
assert_status "$ZRO_E_INPUT" zro_validate_msgid ''
assert_status "$ZRO_E_INPUT" zro_validate_msgid

it "judges the identifier itself, never one still in its delimiters"
# A header's angle brackets are taken off before this function sees the value —
# see zro_trace_msgid_bare, and the cases for it in tests/test_delivery.sh. So a
# value still wearing one is either a second wrapper or half of one, and
# accepting it would mean searching for one string while printing another.
assert_status "$ZRO_E_INPUT" zro_validate_msgid '<CAabc123@example.com>'
assert_status "$ZRO_E_INPUT" zro_validate_msgid '<CAabc123@example.com'
assert_status "$ZRO_E_INPUT" zro_validate_msgid 'CAabc123@example.com>'
# In the middle it is an ordinary character, like everything else here.
assert_ok zro_validate_msgid 'CA<abc>123@example.com'

# The message-id filter is a Perl regular expression like the other two, and an
# identifier carries far more metacharacters than an address does. Bash's own
# engine is the judge here, not our escaping code.
it "a message-id full of metacharacters matches itself once quoted"
# shellcheck disable=SC2016
raw='CA+abc.123$x@mail.example.com'
quoted=$(zro_regex_quote "$raw")
assert_ok zro_validate_msgid "$raw"
if [[ $raw =~ ^${quoted}$ ]]; then
  zro_t_pass
else
  zro_t_fail "quoted message-id does not match itself: $quoted"
fi
# shellcheck disable=SC2016
if [[ 'CAabcX123$x@mail.example.com' =~ ^${quoted}$ ]]; then
  zro_t_fail "quoted message-id widened into a pattern: $quoted"
else
  zro_t_pass
fi

it "accepts a date and time an operator would type"
assert_ok zro_validate_datetime '2026-07-28 08:00'
assert_ok zro_validate_datetime '2026-07-28 08:00:30'
assert_ok zro_validate_datetime '2026-07-28 00:00:00'
assert_ok zro_validate_datetime '2026-07-28 23:59:59'
# '08' is a valid hour and an invalid octal number. Without base-10 arithmetic
# this function refuses eight o'clock.
assert_ok zro_validate_datetime '2026-08-09 08:09'
assert_ok zro_validate_datetime '2026-01-01 00:08:09'

it "requires the time part rather than guessing it"
# A bare date on both ends is a window of zero width: every log the operator
# asked for is read and nothing is found, which reads as an answer it has not
# earned. The whole-day case is what the presets are for.
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-07-28'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-07'

it "rejects a value outside the calendar's own ranges"
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-13-01 08:00'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-00-01 08:00'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-07-32 08:00'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-07-00 08:00'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-07-28 24:00'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-07-28 08:60'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-07-28 08:00:60'
# Before syslog files exist to hold it.
assert_status "$ZRO_E_INPUT" zro_validate_datetime '1969-12-31 23:59'

it "rejects a malformed date and time"
assert_status "$ZRO_E_INPUT" zro_validate_datetime ''
assert_status "$ZRO_E_INPUT" zro_validate_datetime
assert_status "$ZRO_E_INPUT" zro_validate_datetime 'dun'
assert_status "$ZRO_E_INPUT" zro_validate_datetime 'yesterday'
assert_status "$ZRO_E_INPUT" zro_validate_datetime 'now'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '26-07-28 08:00'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-7-28 08:00'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026/07/28 08:00'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-07-28T08:00'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-07-28  08:00'
assert_status "$ZRO_E_INPUT" zro_validate_datetime ' 2026-07-28 08:00'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-07-28 08:00 '
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-07-28 08:00:30:40'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '20260728080000'

it "rejects anything a shell or a command line would read as more than a value"
# The explicit range is the only path that hands operator text to the clock, so
# this table is the one standing between a prompt and 'date -d'.
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-07-28 08:00; id'
# shellcheck disable=SC2016
assert_status "$ZRO_E_INPUT" zro_validate_datetime '$(id)'
# shellcheck disable=SC2016
assert_status "$ZRO_E_INPUT" zro_validate_datetime '`id`'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '2026-07-28 08:00 | cat'
assert_status "$ZRO_E_INPUT" zro_validate_datetime '-2026-07-28 08:00'
assert_status "$ZRO_E_INPUT" zro_validate_datetime $'2026-07-28 08:00\n2026-07-29 08:00'
assert_status "$ZRO_E_INPUT" zro_validate_datetime $'2026-07-28\t08:00'

# ------------------------------------------------------- a folder path ------
#
# PERMISSIVE ABOUT THE NAME, and that is the decision rather than an oversight. A
# folder is named by the account holder, in their own language, with whatever
# punctuation they typed — and the value never becomes a command name: it travels
# as one element of an argument vector, alongside a subcommand the allowlist
# approved. What is refused is what would stop it being ONE PATH.

it "admits the folder paths a real mailbox carries"
assert_ok zro_validate_folder_path '/'
assert_ok zro_validate_folder_path '/Inbox'
# Ships with every mailbox Zimbra creates, space and all.
assert_ok zro_validate_folder_path '/Emailed Contacts'
assert_ok zro_validate_folder_path '/Proje/2026/Q3'
assert_ok zro_validate_folder_path '/Rapor (2026)'
assert_ok zro_validate_folder_path '/Musteri & Tedarikci'
assert_ok zro_validate_folder_path '/Fatura #17'
assert_ok zro_validate_folder_path "/Ahmet'in klasoru"

it "and refuses anything that is not one path"
# Rooted, because every path the folder listing prints is. A value that does not
# begin with '/' is a folder id, a decoration, or something that was never a path
# — and requiring the '/' is also what makes the leading dash every other
# validator has to refuse impossible here.
assert_status "$ZRO_E_INPUT" zro_validate_folder_path ''
assert_status "$ZRO_E_INPUT" zro_validate_folder_path 'Inbox'
assert_status "$ZRO_E_INPUT" zro_validate_folder_path '-v'
assert_status "$ZRO_E_INPUT" zro_validate_folder_path '--json'
assert_status "$ZRO_E_INPUT" zro_validate_folder_path ' /Inbox'
# A control character would be a second line in the report that says which folder
# was read, and in every log line this program writes about it.
assert_status "$ZRO_E_INPUT" zro_validate_folder_path $'/In\nbox'
assert_status "$ZRO_E_INPUT" zro_validate_folder_path $'/In\tbox'
assert_status "$ZRO_E_INPUT" zro_validate_folder_path $'/Inbox\r'

it "and bounds the length of one"
long=$(printf '/%s' "$(head -c 1023 /dev/zero | tr '\0' 'a')")
assert_ok zro_validate_folder_path "$long"
assert_status "$ZRO_E_INPUT" zro_validate_folder_path "$long$long"

it "validates bare domains"
assert_ok zro_validate_domain 'example.com'
assert_ok zro_validate_domain 'mail.example.co.uk'
assert_status "$ZRO_E_INPUT" zro_validate_domain '@example.com'
assert_status "$ZRO_E_INPUT" zro_validate_domain 'example'
assert_status "$ZRO_E_INPUT" zro_validate_domain 'exa mple.com'
assert_status "$ZRO_E_INPUT" zro_validate_domain 'example.com; id'

# ------------------------------------------- the query language's quoting --

it "wraps a value for the query language and escapes the one character that is special"
# Zimbra's own rule, from Query.java: inside a quoted term a literal double quote
# is written \" and NOTHING else is escaped. Measured against the server on
# 2026-08-03: a subject really containing quotes is found by the escaped form.
assert_out_eq '"fatura"' zro_query_quote 'fatura'
assert_out_eq '"iki kelime"' zro_query_quote 'iki kelime'
assert_out_eq '"a \"b\" c"' zro_query_quote 'a "b" c'
assert_out_eq '"ali+fatura@example.com"' zro_query_quote 'ali+fatura@example.com'

it "and leaves every other character alone, the backslash included"
# The design draft doubled backslashes. Zimbra's unescaper only ever collapses
# the two-character sequence \" — a doubled backslash is not collapsed, so
# 'C:\rapor' would be searched for as 'C:\\rapor'.
assert_out_eq '"C:\rapor"' zro_query_quote 'C:\rapor'
assert_out_eq '"a\b"' zro_query_quote 'a\b'
assert_out_eq '"(x) OR -y*"' zro_query_quote '(x) OR -y*'
assert_out_eq '"in:inbox"' zro_query_quote 'in:inbox'

it "and refuses a value that could terminate its own quoting"
# THE CASE THIS FUNCTION EXISTS FOR. A trailing backslash pairs with the closing
# quote: measured on TEST-C, alone at the end of a query the lexer backtracks and
# silently searches for a DIFFERENT value, and with another quoted criterion
# behind it the closing quote is swallowed and the whole query fails to parse.
# Neither may be passed on, and no amount of escaping avoids it — so it is
# refused. See docs/research/2026-08-03-message-search-and-conversations.md §6.
# Written as $'…' so the backslash is unambiguous to a reader and to ShellCheck:
# in single quotes a trailing one reads like an attempt to escape the quote.
assert_status "$ZRO_E_INPUT" zro_query_quote $'fatura\\'
assert_status "$ZRO_E_INPUT" zro_query_quote $'fatura\\\\'
assert_status "$ZRO_E_INPUT" zro_query_quote $'\\'
assert_status "$ZRO_E_INPUT" zro_query_quote $'a "b" \\'

it "and refuses what would stop being one value"
# A newline cannot appear inside a quoted term at all — the grammar excludes it,
# so the query would not lex — and a control character is a second line in every
# report and log line this program writes about the search.
assert_status "$ZRO_E_INPUT" zro_query_quote ''
assert_status "$ZRO_E_INPUT" zro_query_quote
assert_status "$ZRO_E_INPUT" zro_query_quote $'iki\nsatir'
assert_status "$ZRO_E_INPUT" zro_query_quote $'sekme\there'
assert_status "$ZRO_E_INPUT" zro_query_quote $'fatura\r'

it "and the escaped form of a quote survives being read back"
# The round trip Zimbra's unescaper makes: it replaces the two-character
# sequence backslash-quote with a quote and touches nothing else. A value
# carrying a backslash IN FRONT of a quote is the case that would break a rule
# written the other way round, so it is checked rather than reasoned about.
quoted=$(zro_query_quote 'a\"b')
assert_eq "$quoted" '"a\\"b"'
inner=${quoted#\"}
inner=${inner%\"}
assert_eq "${inner//\\\"/\"}" 'a\"b'

# ---------------------------------------------------------- item ids --

it "validates an item id as the digits it is"
assert_ok zro_validate_item_id '1'
assert_ok zro_validate_item_id '265'
assert_ok zro_validate_item_id '2147483647'

it "and refuses a negative one, which is a virtual conversation and not an id this tool may send"
# Zimbra names a conversation holding ONE message with the negation of that
# message's id. The CLI accepts it; the exec gate cannot, because a token shaped
# like a flag in the data position is looked up in the allowlist.
assert_status "$ZRO_E_INPUT" zro_validate_item_id '-263'
assert_status "$ZRO_E_INPUT" zro_validate_item_id '-1'
assert_status "$ZRO_E_INPUT" zro_validate_item_id ''
assert_status "$ZRO_E_INPUT" zro_validate_item_id
assert_status "$ZRO_E_INPUT" zro_validate_item_id 'abc'
assert_status "$ZRO_E_INPUT" zro_validate_item_id '26 5'
assert_status "$ZRO_E_INPUT" zro_validate_item_id '2.65'
assert_status "$ZRO_E_INPUT" zro_validate_item_id '+265'
assert_status "$ZRO_E_INPUT" zro_validate_item_id '0'
assert_status "$ZRO_E_INPUT" zro_validate_item_id '00265'
assert_status "$ZRO_E_INPUT" zro_validate_item_id '99999999999999999999'

zro_t_report
